language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then
      composer install --ignore-platform-reqs
    else
      composer install
    fi

script:
  - ./vendor/bin/phpunit
